import './js/covers.js';
import './js/reviews.js';
import './js/reviews-swiper.js';
import './js/benefits.js'
import './js/faq.js'
import './js/header.js'
import './js/hero.js'
import './js/projects.js'
import './js/work-together.js'
import './js/about-me.js'
import './js/about-me-2.js'